apiVersion: apps/v1
kind: Deployment
metadata:
  name: Ajio-clone-deployment
  labels:
    app: example
spec:
  replicas: 3
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
        - name: Ajio-clone
          image: levinjenson/ajio-clone-devops:latest
          ports:
            - containerPort: 8081
